language: java

services:
  - docker

before_install:
  - chmod +x mvnw
  - docker build -t jonug84/test .
  - docker run -d -p 127.0.0.1:80:4567 jonug84/test 
  - docker ps -a 

sudo: true
addons:
    sonarcloud:
        organization: "jonatanuribe"
        token:
            secure: P5yB5UYxEyKhiLmU+ezQ42KpPBvYFgeugrypgLejUERjzC2Flwy75DkfbmF6RxJI4NWTbJSTAfZbfYED32K03Q3mexsTkiwcruVgrirUuTMbktcVu+iKpcxMGWPjR/+02QnyeCtL3Gcek52qtWjXVFMNitAPLmiahYkYEHT91s/VhZLx/V14jQpxsFaLohuT49bfWuK28FmXExWrRlncTJ+01mH3OiaspKgFelc3b6zmS0enRvxj5GyYdWa3YlKpAM4VvAIofRr/8frrukTnvPY0k+R4UD3wS3ej59iaNG2xgq6N83F+xokf4anD3YDim6+9uXJ+wMIW331MdKqaDWmuQiZ/lx1z7MRqNUe1+Mism/ZDJecs16oG6UiMDf3Q/POmsH6FLpUeineERyCJaKmobtp37LRDtFReTjAcODr3TSifcdZyrEoRHRgcGMlFWYoetQhyq1L6JkMF66oWOcM76KaVBkvGbOJo3y9Z9leOlCtGCyhfnBN29RZqqthwyGntu8Vo5PyxJ2X6PZQcK2p0odWF2gLFcVto8qmARJ9cNHv/Yg/MlLpVc0ZGGEoinYwt+hAZaYDrjosuWTELcTak4Yn5S/HgyOC0u0XxBC9PvcdeHoPUpPGl8Nmb3bB8PeozGgG86aBllJ6jMQlh5+PTjNyKbDxrVR1hUQcf1xk=
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success:
  - if [ "$TRAVIS_BRANCH" == "jonatanuribe" ]; then
    docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD";
    docker push jonug84/test;
    fi